platform :ios, '11.0'

target 'Enhance' do

  use_frameworks!

  # Pods for Enhance
pod 'Hero'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'SkeletonView'
pod "Counter"
pod 'PopupDialog', '~> 1.1'
pod 'STopAlert'
pod 'TransitionButton'

end
